# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        our_db_provider:
            entity:
                class: AppBundle:Users
                property: email

    encoders:
        AppBundle\Entity\Users: sha512

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

            form_login:
                provider: our_db_provider
                csrf_provider: security.csrf.token_manager
                check_path: /login_check
                login_path: /
                default_target_path: /before
                failure_path: /

                username_parameter: email
                password_parameter: pass

            logout:
                path: /logout

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        - { path: ^/before, roles: ROLE_USER }
        - { path: ^/quiz, roles: ROLE_USER }
        - { path: ^/thx, roles: ROLE_USER }