kata_homepage:
    path:     /
    defaults:
      _controller: KataBundle:Default:index

kata_adress:
    path:     /adress
    defaults:
      _controller: KataBundle:Default:adress


kata_user:
    path: /user
    defaults:
      _controller: KataBundle:Default:user