<?php

namespace AppBundle\Entity;

/**
 * QuestionToUserSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionToUserSetRepository extends \Doctrine\ORM\EntityRepository
{
}
