<?php

namespace AppBundle\Entity;
use Doctrine\ORM\NoResultException;
/**
 * QuizsetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizsetRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNearest(){
        try{
            $quiz = $this->getEntityManager()
                ->createQueryBuilder()
                ->select('q')
                ->from('AppBundle:Quizset','q')
                ->where('q.dateEnd >= :date' )
                ->orderBy('q.dateEnd', 'DESC')
                ->setParameter(':date', date('Y-m-d H:i:s'))
                ->getQuery()
                ->getSingleResult();

            if(! $quiz ) return false;
            return $quiz;
        } catch( NoResultException $e){
            return false;
        }
    }

}
