<?php

namespace AppBundle\Entity;

/**
 * UsersToQuizsetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersToQuizsetRepository extends \Doctrine\ORM\EntityRepository
{
}
